variables:
- group: ServiceConnection-PRD1
- name: docker.imageName
  value: 'eprpaymentfrontend'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'eprpaymentfrontendrepository'
- name: serviceName
  value: 'prdrwdwebwa1423'
